[tool.poetry]
name = "graphsec-detector"
version = "0.1.0"
description = ""
authors = ["Jake Hulme"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26"
requests = "^2.32.4"
urllib3 = "^2.5.0"
transformers = {version = "^4.52.4", extras = ["tf"]}
tensorflow = "2.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
